#index:
#    path: /
#    controller: App\Controller\DefaultController::index

laskePalkka:
  path: /esimerkki/esim1
  controller: App\Controller\ExampleController::laskePalkka

karkausvuosi:
  path: /esimerkki/esim2
  controller: App\Controller\ExampleController::tarkistaKarkausvuosi

vesiPH:
  path: /esimerkki/esim3
  controller: App\Controller\ExampleController::laskePH

heitaNoppaa:
  path: /esimerkki/esim4
  controller: App\Controller\ExampleController::heitaNoppaa

naytaJSON:
  path: /esimerkki/esim5
  controller: App\Controller\ExampleController::naytaJSON

lihapiirakka:
  path: /esimerkki/esim6
  controller: App\Controller\ExampleController::lihapiirakka



